# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsQiWJZPubhkUoTvUIbzMlWTVvUdmoVp
"""

#open a text file in 'Write'mode to write the given lines
f=open("D:\textfile.txt",'w')
f.write("first line\n")
f.write("second line\n")
f.write("third line\n")
f.close()
#Open a text file in read mode to read and print the available lines-readline function
k=open("D:\textfile.txt",'r')
print(k.readline())
print(k.readline())
print(k.readline())
k.close()

#open a text file in 'Append' mode to add/append new line inputs
m=open ("D:\\textfile.txt",'a')
m.write("fourth line\n")
m.write("fifth line\n")
m.close()
#open a text file 'Read' mode to readand print the avilable full text -read fuction
p=open("D:\\textfile.txt",'r')
print(p.read())
p.close()

with open("D:\textfile.txt",'r') as file:
  lines=file.readlines()
  print(lines)

import json
#JSON string
x='{"name":"john","age":30,"city":"New York"}'
#CONVERT JSON string to python dictionary
y=json.loads(x)
print(y["age"])

#python dictionary
data={
    "name":"John",
  "age":30,
  "city":"New York"
}
#convert python dictionary to JSON
json_data=json.dumps(data)
print(json_data)

